/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LegalSlugRouteImport } from './routes/legal/$slug'
import { Route as AdminVipRouteImport } from './routes/admin.vip'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPaymentMethodsRouteImport } from './routes/admin.payment-methods'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminInstagramRouteImport } from './routes/admin.instagram'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBroadcastRouteImport } from './routes/admin.broadcast'
import { Route as AdminBlockedRouteImport } from './routes/admin.blocked'
import { Route as AdminVipIndexRouteImport } from './routes/admin.vip.index'
import { Route as ApiCronEnsureWebhookRouteImport } from './routes/api/cron/ensure-webhook'
import { Route as ApiCronBroadcastRouteImport } from './routes/api/cron/broadcast'
import { Route as ApiAdminUploadRouteImport } from './routes/api/admin/upload'
import { Route as AdminVipTariffsRouteImport } from './routes/admin.vip.tariffs'
import { Route as AdminVipSubscribersRouteImport } from './routes/admin.vip.subscribers'
import { Route as AdminVipSettingsRouteImport } from './routes/admin.vip.settings'
import { Route as ApiPublicZernioWebhookRouteImport } from './routes/api/public/zernio/webhook'
import { Route as ApiPublicVipCronRouteImport } from './routes/api/public/vip/cron'
import { Route as ApiPublicTelegramWebhookVipRouteImport } from './routes/api/public/telegram/webhook-vip'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicRobokassaSuccessRouteImport } from './routes/api/public/robokassa/success'
import { Route as ApiPublicRobokassaResultRouteImport } from './routes/api/public/robokassa/result'
import { Route as ApiPublicRobokassaFailRouteImport } from './routes/api/public/robokassa/fail'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img/$'
import { Route as ApiAdminFileSplatRouteImport } from './routes/api/admin/file/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVipRoute = AdminVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentMethodsRoute = AdminPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstagramRoute = AdminInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlockedRoute = AdminBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVipIndexRoute = AdminVipIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminVipRoute,
} as any)
const ApiCronEnsureWebhookRoute = ApiCronEnsureWebhookRouteImport.update({
  id: '/api/cron/ensure-webhook',
  path: '/api/cron/ensure-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronBroadcastRoute = ApiCronBroadcastRouteImport.update({
  id: '/api/cron/broadcast',
  path: '/api/cron/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVipTariffsRoute = AdminVipTariffsRouteImport.update({
  id: '/tariffs',
  path: '/tariffs',
  getParentRoute: () => AdminVipRoute,
} as any)
const AdminVipSubscribersRoute = AdminVipSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminVipRoute,
} as any)
const AdminVipSettingsRoute = AdminVipSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminVipRoute,
} as any)
const ApiPublicZernioWebhookRoute = ApiPublicZernioWebhookRouteImport.update({
  id: '/api/public/zernio/webhook',
  path: '/api/public/zernio/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVipCronRoute = ApiPublicVipCronRouteImport.update({
  id: '/api/public/vip/cron',
  path: '/api/public/vip/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookVipRoute =
  ApiPublicTelegramWebhookVipRouteImport.update({
    id: '/api/public/telegram/webhook-vip',
    path: '/api/public/telegram/webhook-vip',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRobokassaSuccessRoute =
  ApiPublicRobokassaSuccessRouteImport.update({
    id: '/api/public/robokassa/success',
    path: '/api/public/robokassa/success',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRobokassaResultRoute =
  ApiPublicRobokassaResultRouteImport.update({
    id: '/api/public/robokassa/result',
    path: '/api/public/robokassa/result',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRobokassaFailRoute = ApiPublicRobokassaFailRouteImport.update({
  id: '/api/public/robokassa/fail',
  path: '/api/public/robokassa/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFileSplatRoute = ApiAdminFileSplatRouteImport.update({
  id: '/api/admin/file/$',
  path: '/api/admin/file/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/blocked': typeof AdminBlockedRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vip': typeof AdminVipRouteWithChildren
  '/legal/$slug': typeof LegalSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/vip/settings': typeof AdminVipSettingsRoute
  '/admin/vip/subscribers': typeof AdminVipSubscribersRoute
  '/admin/vip/tariffs': typeof AdminVipTariffsRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/cron/broadcast': typeof ApiCronBroadcastRoute
  '/api/cron/ensure-webhook': typeof ApiCronEnsureWebhookRoute
  '/admin/vip/': typeof AdminVipIndexRoute
  '/api/admin/file/$': typeof ApiAdminFileSplatRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/robokassa/fail': typeof ApiPublicRobokassaFailRoute
  '/api/public/robokassa/result': typeof ApiPublicRobokassaResultRoute
  '/api/public/robokassa/success': typeof ApiPublicRobokassaSuccessRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telegram/webhook-vip': typeof ApiPublicTelegramWebhookVipRoute
  '/api/public/vip/cron': typeof ApiPublicVipCronRoute
  '/api/public/zernio/webhook': typeof ApiPublicZernioWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/blocked': typeof AdminBlockedRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/vip/settings': typeof AdminVipSettingsRoute
  '/admin/vip/subscribers': typeof AdminVipSubscribersRoute
  '/admin/vip/tariffs': typeof AdminVipTariffsRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/cron/broadcast': typeof ApiCronBroadcastRoute
  '/api/cron/ensure-webhook': typeof ApiCronEnsureWebhookRoute
  '/admin/vip': typeof AdminVipIndexRoute
  '/api/admin/file/$': typeof ApiAdminFileSplatRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/robokassa/fail': typeof ApiPublicRobokassaFailRoute
  '/api/public/robokassa/result': typeof ApiPublicRobokassaResultRoute
  '/api/public/robokassa/success': typeof ApiPublicRobokassaSuccessRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telegram/webhook-vip': typeof ApiPublicTelegramWebhookVipRoute
  '/api/public/vip/cron': typeof ApiPublicVipCronRoute
  '/api/public/zernio/webhook': typeof ApiPublicZernioWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/blocked': typeof AdminBlockedRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vip': typeof AdminVipRouteWithChildren
  '/legal/$slug': typeof LegalSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/vip/settings': typeof AdminVipSettingsRoute
  '/admin/vip/subscribers': typeof AdminVipSubscribersRoute
  '/admin/vip/tariffs': typeof AdminVipTariffsRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/cron/broadcast': typeof ApiCronBroadcastRoute
  '/api/cron/ensure-webhook': typeof ApiCronEnsureWebhookRoute
  '/admin/vip/': typeof AdminVipIndexRoute
  '/api/admin/file/$': typeof ApiAdminFileSplatRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/robokassa/fail': typeof ApiPublicRobokassaFailRoute
  '/api/public/robokassa/result': typeof ApiPublicRobokassaResultRoute
  '/api/public/robokassa/success': typeof ApiPublicRobokassaSuccessRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telegram/webhook-vip': typeof ApiPublicTelegramWebhookVipRoute
  '/api/public/vip/cron': typeof ApiPublicVipCronRoute
  '/api/public/zernio/webhook': typeof ApiPublicZernioWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/blocked'
    | '/admin/broadcast'
    | '/admin/categories'
    | '/admin/instagram'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/vip'
    | '/legal/$slug'
    | '/admin/'
    | '/admin/vip/settings'
    | '/admin/vip/subscribers'
    | '/admin/vip/tariffs'
    | '/api/admin/upload'
    | '/api/cron/broadcast'
    | '/api/cron/ensure-webhook'
    | '/admin/vip/'
    | '/api/admin/file/$'
    | '/api/public/img/$'
    | '/api/public/robokassa/fail'
    | '/api/public/robokassa/result'
    | '/api/public/robokassa/success'
    | '/api/public/telegram/webhook'
    | '/api/public/telegram/webhook-vip'
    | '/api/public/vip/cron'
    | '/api/public/zernio/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/blocked'
    | '/admin/broadcast'
    | '/admin/categories'
    | '/admin/instagram'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/products'
    | '/admin/settings'
    | '/legal/$slug'
    | '/admin'
    | '/admin/vip/settings'
    | '/admin/vip/subscribers'
    | '/admin/vip/tariffs'
    | '/api/admin/upload'
    | '/api/cron/broadcast'
    | '/api/cron/ensure-webhook'
    | '/admin/vip'
    | '/api/admin/file/$'
    | '/api/public/img/$'
    | '/api/public/robokassa/fail'
    | '/api/public/robokassa/result'
    | '/api/public/robokassa/success'
    | '/api/public/telegram/webhook'
    | '/api/public/telegram/webhook-vip'
    | '/api/public/vip/cron'
    | '/api/public/zernio/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/blocked'
    | '/admin/broadcast'
    | '/admin/categories'
    | '/admin/instagram'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/vip'
    | '/legal/$slug'
    | '/admin/'
    | '/admin/vip/settings'
    | '/admin/vip/subscribers'
    | '/admin/vip/tariffs'
    | '/api/admin/upload'
    | '/api/cron/broadcast'
    | '/api/cron/ensure-webhook'
    | '/admin/vip/'
    | '/api/admin/file/$'
    | '/api/public/img/$'
    | '/api/public/robokassa/fail'
    | '/api/public/robokassa/result'
    | '/api/public/robokassa/success'
    | '/api/public/telegram/webhook'
    | '/api/public/telegram/webhook-vip'
    | '/api/public/vip/cron'
    | '/api/public/zernio/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
  ApiCronBroadcastRoute: typeof ApiCronBroadcastRoute
  ApiCronEnsureWebhookRoute: typeof ApiCronEnsureWebhookRoute
  ApiAdminFileSplatRoute: typeof ApiAdminFileSplatRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
  ApiPublicRobokassaFailRoute: typeof ApiPublicRobokassaFailRoute
  ApiPublicRobokassaResultRoute: typeof ApiPublicRobokassaResultRoute
  ApiPublicRobokassaSuccessRoute: typeof ApiPublicRobokassaSuccessRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicTelegramWebhookVipRoute: typeof ApiPublicTelegramWebhookVipRoute
  ApiPublicVipCronRoute: typeof ApiPublicVipCronRoute
  ApiPublicZernioWebhookRoute: typeof ApiPublicZernioWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vip': {
      id: '/admin/vip'
      path: '/vip'
      fullPath: '/admin/vip'
      preLoaderRoute: typeof AdminVipRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-methods': {
      id: '/admin/payment-methods'
      path: '/payment-methods'
      fullPath: '/admin/payment-methods'
      preLoaderRoute: typeof AdminPaymentMethodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instagram': {
      id: '/admin/instagram'
      path: '/instagram'
      fullPath: '/admin/instagram'
      preLoaderRoute: typeof AdminInstagramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcast': {
      id: '/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AdminBroadcastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blocked': {
      id: '/admin/blocked'
      path: '/blocked'
      fullPath: '/admin/blocked'
      preLoaderRoute: typeof AdminBlockedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vip/': {
      id: '/admin/vip/'
      path: '/'
      fullPath: '/admin/vip/'
      preLoaderRoute: typeof AdminVipIndexRouteImport
      parentRoute: typeof AdminVipRoute
    }
    '/api/cron/ensure-webhook': {
      id: '/api/cron/ensure-webhook'
      path: '/api/cron/ensure-webhook'
      fullPath: '/api/cron/ensure-webhook'
      preLoaderRoute: typeof ApiCronEnsureWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/broadcast': {
      id: '/api/cron/broadcast'
      path: '/api/cron/broadcast'
      fullPath: '/api/cron/broadcast'
      preLoaderRoute: typeof ApiCronBroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vip/tariffs': {
      id: '/admin/vip/tariffs'
      path: '/tariffs'
      fullPath: '/admin/vip/tariffs'
      preLoaderRoute: typeof AdminVipTariffsRouteImport
      parentRoute: typeof AdminVipRoute
    }
    '/admin/vip/subscribers': {
      id: '/admin/vip/subscribers'
      path: '/subscribers'
      fullPath: '/admin/vip/subscribers'
      preLoaderRoute: typeof AdminVipSubscribersRouteImport
      parentRoute: typeof AdminVipRoute
    }
    '/admin/vip/settings': {
      id: '/admin/vip/settings'
      path: '/settings'
      fullPath: '/admin/vip/settings'
      preLoaderRoute: typeof AdminVipSettingsRouteImport
      parentRoute: typeof AdminVipRoute
    }
    '/api/public/zernio/webhook': {
      id: '/api/public/zernio/webhook'
      path: '/api/public/zernio/webhook'
      fullPath: '/api/public/zernio/webhook'
      preLoaderRoute: typeof ApiPublicZernioWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vip/cron': {
      id: '/api/public/vip/cron'
      path: '/api/public/vip/cron'
      fullPath: '/api/public/vip/cron'
      preLoaderRoute: typeof ApiPublicVipCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook-vip': {
      id: '/api/public/telegram/webhook-vip'
      path: '/api/public/telegram/webhook-vip'
      fullPath: '/api/public/telegram/webhook-vip'
      preLoaderRoute: typeof ApiPublicTelegramWebhookVipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robokassa/success': {
      id: '/api/public/robokassa/success'
      path: '/api/public/robokassa/success'
      fullPath: '/api/public/robokassa/success'
      preLoaderRoute: typeof ApiPublicRobokassaSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robokassa/result': {
      id: '/api/public/robokassa/result'
      path: '/api/public/robokassa/result'
      fullPath: '/api/public/robokassa/result'
      preLoaderRoute: typeof ApiPublicRobokassaResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robokassa/fail': {
      id: '/api/public/robokassa/fail'
      path: '/api/public/robokassa/fail'
      fullPath: '/api/public/robokassa/fail'
      preLoaderRoute: typeof ApiPublicRobokassaFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/file/$': {
      id: '/api/admin/file/$'
      path: '/api/admin/file/$'
      fullPath: '/api/admin/file/$'
      preLoaderRoute: typeof ApiAdminFileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminVipRouteChildren {
  AdminVipSettingsRoute: typeof AdminVipSettingsRoute
  AdminVipSubscribersRoute: typeof AdminVipSubscribersRoute
  AdminVipTariffsRoute: typeof AdminVipTariffsRoute
  AdminVipIndexRoute: typeof AdminVipIndexRoute
}

const AdminVipRouteChildren: AdminVipRouteChildren = {
  AdminVipSettingsRoute: AdminVipSettingsRoute,
  AdminVipSubscribersRoute: AdminVipSubscribersRoute,
  AdminVipTariffsRoute: AdminVipTariffsRoute,
  AdminVipIndexRoute: AdminVipIndexRoute,
}

const AdminVipRouteWithChildren = AdminVipRoute._addFileChildren(
  AdminVipRouteChildren,
)

interface AdminRouteChildren {
  AdminBlockedRoute: typeof AdminBlockedRoute
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminInstagramRoute: typeof AdminInstagramRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentMethodsRoute: typeof AdminPaymentMethodsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminVipRoute: typeof AdminVipRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlockedRoute: AdminBlockedRoute,
  AdminBroadcastRoute: AdminBroadcastRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminInstagramRoute: AdminInstagramRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentMethodsRoute: AdminPaymentMethodsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminVipRoute: AdminVipRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  LegalSlugRoute: LegalSlugRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
  ApiCronBroadcastRoute: ApiCronBroadcastRoute,
  ApiCronEnsureWebhookRoute: ApiCronEnsureWebhookRoute,
  ApiAdminFileSplatRoute: ApiAdminFileSplatRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
  ApiPublicRobokassaFailRoute: ApiPublicRobokassaFailRoute,
  ApiPublicRobokassaResultRoute: ApiPublicRobokassaResultRoute,
  ApiPublicRobokassaSuccessRoute: ApiPublicRobokassaSuccessRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicTelegramWebhookVipRoute: ApiPublicTelegramWebhookVipRoute,
  ApiPublicVipCronRoute: ApiPublicVipCronRoute,
  ApiPublicZernioWebhookRoute: ApiPublicZernioWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
